#!/bin/bash -x

INPUT_CLIP_PATH=$1
INPUT_CLIP_NAME=${INPUT_CLIP_PATH##*/}
INPUT_CLIP_NAME=${INPUT_CLIP_NAME%.*}
INPUT_CLIP_DURATION="$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $INPUT_CLIP_PATH)"
INPUT_CLIP_DURATION=${INPUT_CLIP_DURATION%.*}
OUTPUT_CLIP_DURATION=$2
FINGER=0

while [ $FINGER -le $INPUT_CLIP_DURATION ]; do
	ffmpeg -ss $FINGER -i ${INPUT_CLIP_PATH} -t $OUTPUT_CLIP_DURATION -c:v copy ${INPUT_CLIP_NAME}-part-${FINGER}.mp4
	let "FINGER=FINGER+${OUTPUT_CLIP_DURATION}"
done

